on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build -c Release .\Source\ISeriesProvider\LinqToDB.DataProvider.DB2iSeries.csproj
    - name: Pack
      run: dotnet pack -c Release --include-symbols --include-source .\Source\ISeriesProvider\LinqToDB.DataProvider.DB2iSeries.csproj --no-build --output .
    - name: Push
      run: dotnet nuget push *.nupkg --source https://www.myget.org/F/nsarristest/api/v3/index.json --api-key ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.MYGET_API_KEY }}
